// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The source the UI is currently scoped to: which catalog the sidebar, search
 * and capability gating reflect.
 *
 * This is a **browse-scope** marker only: it never changes playback routing
 * (that stays URI-scheme driven via `route_local_event` + `App::local_playback`),
 * so switching the active source never interrupts what is currently playing.
 *
 * The enum is deliberately unconditional: every variant compiles in every
 * build (including the slim `telemetry`-only CI build) so handlers and UI code
 * never need `#[cfg]`. Only the per-source *data loading* is gated behind that
 * source's feature (`local-files`, `subsonic`).
 *
 * The serde derives are the action-vocabulary wire shape; the derived unit-
 * variant strings coincide with the `to_config_str()` tokens, while the
 * `state.yml` persistence keeps its own lenient hand-written helpers.
 */
export type Source = "Spotify" | "Local" | "Subsonic" | "Radio" | "YouTube" | "Qobuz" | "Tidal";
