// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistInfo } from "./PlaylistInfo";
import type { TrackInfo } from "./TrackInfo";

/**
 * Every source's sidebar list; the page shows the one for the active source.
 */
export type SourcePlaylists = { spotify: Array<PlaylistInfo>, local: Array<PlaylistInfo>, subsonic: Array<PlaylistInfo>, qobuz: Array<PlaylistInfo>, tidal: Array<PlaylistInfo>, youtube: Array<PlaylistInfo>, 
/**
 * Stations are playable rows (`radio:<url>`), not playlists.
 */
radio: Array<TrackInfo>, };
